### ISSUE TITLE
Make Elasticsearch optional

### ISSUE THREAD

**Issue by joekendal** [awslabs/fhir-works-on-aws-interface#50]
Currently `typeSearch` is a required param for resources in the fhirConfig. This makes it difficult to remove elasticsearch without changing multiple repositories and maintaining separate forks.

Instead it would be better if left as an optional requirement in the config

**Comment by rsmayda** [comment]
Great feedback we will loop this into our upcoming retrospective to discuss. We do have the [stubs](https://github.com/awslabs/fhir-works-on-aws-interface/blob/mainline/src/stubs.ts) that should be used in these cases. The goal in this approach is to explicitly see that you are stubbing out `typeSearch`.

A thing to note that routing is determined by which operations you claim to support: https://github.com/awslabs/fhir-works-on-aws-routing/blob/8134be9422fce238c205532a78f915c26dc40834/src/router/routes/genericResourceRoute.ts#L129

I think there is an opportunity here to make this simpler to understand.

**Comment by joekendal** [comment]
I think your last point here is key.

We would be interested in some internal design documents if they could be released.

This code is useful indeed but dedicated docs are what we're looking for so we can customise it easily.

I would also add that there are a lot of files and a lot of things to try and follow between multiple files and repositories. We are re-writing large parts of this project so that it uses a clean Terraform codebase instead of all this messy cloudformation and bash scripting. This makes it easier to read, understand and maintain. It will be released to the public eventually and help healthcare providers in the UK create data lakes. 

I'm aware that AWS healthlake will be available in other regions in the future but for now this provides a nice open source starter template for the community.

I really think AWS should just acquire HashiCorp at this point.

**Comment by rsmayda** [comment]
After discussion we have decided to leave the configuration as is. We want our customers to make a choice when it comes to the configuration, meaning if they don't want ES they should pass in the [stubs](https://github.com/awslabs/fhir-works-on-aws-interface/blob/mainline/src/stubs.ts) and explicitly call out the operations they want to support.

If you have further questions or advice please re-open the ticket!

**Comment by joekendal** [comment]
By default the template deployed a huge elasticsearch instance and ended up costing me quite a bit of money for nothing. It should be the minimum instance size and not a medium. Customers will be shocked when they're just testing something and see their bill after just a few days. It might have been updated since I haven't checked but anyway
