### ISSUE TITLE
Invalid FHIR R4 Resource Type "MedicinalProductOperation" 

### ISSUE THREAD

**Issue by emilhdiaz** [awslabs/fhir-works-on-aws-interface#52]
It appears that `MedicinalProductOperation` is not a valid value in the value set http://hl7.org/fhir/ValueSet/resource-types|4.0.1

From the Aegis reports: 

![Screen Shot 2021-02-18 at 12 11 18 AM](https://user-images.githubusercontent.com/2886234/108308633-11992800-717e-11eb-9c24-5bb4d4f578b6.png)

Perhaps this one should be removed from `src/constants.ts:BASE_R4_RESOURCES`?

**Comment by nguyen102** [comment]
Thank you for bringing this to our attention. I've created a PR for this issue here
https://github.com/awslabs/fhir-works-on-aws-interface/pull/54

**Comment by nguyen102** [comment]
PR merged
https://github.com/awslabs/fhir-works-on-aws-interface/pull/54
